---
# vi: set ft=ansible :
- hosts: db
  sudo: yes
  sudo_user: root
  gather_facts: true
  vars_files:
    - vars/db.yml
  roles:
    - { role: vickumar1981.mysql }
    - { role: geerlingguy.firewall, when: ansible_virtualization_type != 'docker' }

- hosts: app
  sudo: yes
  sudo_user: root
  gather_facts: true
  pre_tasks:
    - name: Install the EPEL package
      yum:
        name: epel-release
        state: present
        update_cache: yes

    - name: yum 
      yum:
        name: '*'
        state: latest
        update_cache: yes
        disablerepo: epel

  vars_files:
    - vars/app.yml
  roles:
    - { role: geerlingguy.java }
    - { role: vccabral.elasticsearch }
    - { role: geerlingguy.git }
    - { role: Ken24.python }
    - { role: geerlingguy.firewall, when: ansible_virtualization_type != 'docker' }
    - { role: smbambling.apache }
    - { role: vickumar1981.nodejs }
  tasks:
    - name: Install python dependencies
      yum: pkg={{ item }} state=present
      with_items:
        - "libtiff-devel"
        - "libjpeg-devel"
        - "libzip-devel"
        - "freetype-devel"
        - "tcl-devel"
        - "tk-devel"
        - "python-devel"
        - "mysql-devel.x86_64"
        - "alsa-lib-devel"
        - "libnotify"
        - "libxslt-devel"
        - "libxml2-devel"

    - name: Add the SLC Repos
      yum_repository:
        name: "{{ item.key }}"
        description: "{{ item.value.description }}"
        file: scl6-devtoolset.repo
        baseurl: "{{ item.value.baseurl }}"
        gpgkey: http://linuxsoft.cern.ch/cern/slc6X/x86_64/RPM-GPG-KEY-cern
        gpgcheck: yes
      with_dict: "{{ slc6_repos }}"

    - name: Install devtoolset-2
      yum:
        pkg: "devtoolset-2"
        state: present

    # PDFReactor
    - name: Download PDFReactor
      get_url: 
        url: http://download.realobjects.de/PDFreactor_6_3_6828_3_unix_installer.tar.gz 
        dest: /opt/PDFreactor_6_3_6828_3_unix_installer.tar.gz 
        force: false

    - name: Untar PDFReactor
      unarchive: 
        src: /opt/PDFreactor_6_3_6828_3_unix_installer.tar.gz 
        dest: /opt 
        copy: no
        creates: /opt/.pdfreactor_untarred

    - name: Start PDFReactor service
      command: /opt/PDFreactor/bin/pdfreactorwebservice start 

    # Django Development Setup
    - name: Install virtualenv
      command: "/usr/local/bin/pip install virtualenv"

    - name: Create virtualenv and install requirements
      pip:
        requirements: /cfpb_app/requirements/local.txt 
        virtualenv: /cfpb_app/cfgov-refresh 
        virtualenv_command: /usr/local/bin/virtualenv

    - name: Add environment variables to bashrc
      lineinfile: 
        dest: /etc/profile 
        state: present 
        regexp: 'source /cfpb_app/cfgov-refresh/bin/activate' 
        line: 'source /cfpb_app/cfgov-refresh/bin/activate; source /vagrant/.env'

    - name: Migrate django db to match application state
      shell: "source /cfpb_app/.env; /cfpb_app/cfgov-refresh/bin/python /cfpb_app/cfgov/manage.py migrate"
